import Foundation
import Security
import CryptoKit

// PokitDeviceKeyStore is the iOS Secure Enclave analogue of the Android
// PokitDeviceKeyStore.kt. It is free of any Expo dependency so XCTest exercises
// the real Security-framework logic directly. The private scalar is created
// inside the Secure Enclave and never leaves it (SecKeyCopyExternalRepresentation
// on the private key fails — that is the non-exportability proof).
//
// Output is byte-identical to the Android provider so the shared JS validator
// (modules/pokit-device-key/src/index.ts) and the Go daemon
// (internal/devicetrust, ecdsa.VerifyASN1 over SHA256(transcript)) accept an iOS
// device with no daemon change:
//   - sign  = ECDSA P-256 over SHA-256(message), ASN.1 DER
//   - SPKI  = 26-byte P-256 header + 65-byte uncompressed point (91 bytes)
//   - deviceId = hex(SHA-256(SPKI))

// Stable error-code vocabulary (mirrored in the TS wrapper `DEVICE_KEY_CODES`
// and the Android `DeviceKeyCodes`). JS logic branches on the code, never the
// message text.
enum DeviceKeyCodes {
  static let keyMissing = "key_missing"
  static let keyInvalidated = "key_invalidated"
  static let keyInaccessible = "key_inaccessible"
  static let hardwareUnavailable = "hardware_unavailable"
  static let keyExportable = "key_exportable"
  static let keyIncompatible = "key_incompatible"
  static let nativeOperationFailed = "native_operation_failed"
  static let deleteFailed = "delete_failed"
}

// Typed device-key failure. `code` is the stable machine-readable identifier;
// `message` is safe (no key material, tag, or provider internals). The Expo
// module maps this to a coded error so JS receives the code independently of the
// message.
struct DeviceKeyError: Error {
  let code: String
  let message: String
  init(_ code: String, _ message: String) { self.code = code; self.message = message }
}

// The canonical 26-byte P-256 SubjectPublicKeyInfo prefix (SEQUENCE + AlgId +
// BIT STRING header). SecKeyCopyExternalRepresentation returns only the 65-byte
// uncompressed point; the daemon and Android emit the full 91-byte SPKI, so the
// point is wrapped with this prefix. Matches src/index.ts SPKI validation.
private let p256SpkiPrefix: [UInt8] = [
  0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01,
  0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x03, 0x42, 0x00,
]

final class PokitDeviceKeyStore {
  // Application tag identifying the one device-identity key in the keychain.
  // Mirrors the Android alias "pokit.device.identity.v1".
  private let tag: Data
  private let lock = NSLock()

  init(tag: String = "pokit.device.identity.v1") {
    self.tag = tag.data(using: .utf8)!
  }

  // ── public surface (mirrors the Android store method set) ──

  func getSupport() -> String {
    // The Secure Enclave is required. On a simulator or a device without an
    // enclave, fail closed as hardware_unavailable — no software-key fallback.
    return SecureEnclave.isAvailable ? "supported" : DeviceKeyCodes.hardwareUnavailable
  }

  // hasKey reports ONLY existence: a missing key is false; an inaccessible /
  // invalidated / native failure propagates as a typed error (never hidden as
  // false), matching the Android/shared contract so the JS wrapper fails closed.
  func hasKey() throws -> Bool {
    do {
      _ = try loadPrivateKey()
      return true
    } catch let e as DeviceKeyError where e.code == DeviceKeyCodes.keyMissing {
      return false
    }
    // Any other DeviceKeyError (key_inaccessible / key_invalidated) propagates.
  }

  // ensureKey is atomic (whole body under lock). Creation ownership is explicit:
  // a key that existed before this call is validated and returned as-is and is
  // NEVER deleted/replaced; a key generated by THIS call that fails validation
  // (before its identity is exposed) is the only thing this call may clean up.
  func ensureKey() throws -> [String: Any] {
    lock.lock()
    defer { lock.unlock() }
    // ONLY an exact key_missing grants this call creation ownership. An
    // inaccessible/invalidated existing identity must NOT be mistaken for
    // "absent" — otherwise a locked device could regenerate the identity or, on
    // rollback, delete a real paired key. Any non-missing error propagates
    // WITHOUT entering the creation path.
    let createdByThisCall: Bool
    do {
      _ = try loadPrivateKey()
      createdByThisCall = false
    } catch let e as DeviceKeyError where e.code == DeviceKeyCodes.keyMissing {
      createdByThisCall = true
    }
    if createdByThisCall {
      try generateKey()
    }
    do {
      return try validate().info
    } catch let e as DeviceKeyError {
      if createdByThisCall {
        // Roll back ONLY a key this call just created; never an existing one.
        // If cleanup itself fails, an unusable alias could remain — surface that
        // as a native failure rather than the (now-misleading) validation error.
        let del = SecItemDelete(baseQuery() as CFDictionary)
        if del != errSecSuccess && del != errSecItemNotFound {
          throw DeviceKeyError(DeviceKeyCodes.nativeOperationFailed, "cleanup of failed new key failed")
        }
      }
      // Existing key: fail closed WITHOUT deleting/replacing it.
      throw e
    }
  }

  func getKeyInfo() throws -> [String: Any] {
    return try validate().info
  }

  func getPublicKeySpki() throws -> String {
    return try validate().spkiHex
  }

  // sign passes the SAME full policy validation as ensureKey/getKeyInfo before
  // producing any signature — a non-Secure-Enclave / non-P256 / exportable key
  // can never sign, even if it already exists at the tag.
  func sign(_ messageHex: String) throws -> String {
    let message = try hexToBytes(messageHex)
    let v = try validate() // full key policy — throws before any signing
    var error: Unmanaged<CFError>?
    guard let sig = SecKeyCreateSignature(
      v.privateKey,
      .ecdsaSignatureMessageX962SHA256, // SHA-256 digest + X9.62 ASN.1 DER
      message as CFData,
      &error
    ) else {
      throw DeviceKeyError(DeviceKeyCodes.nativeOperationFailed, "signing failed")
    }
    return bytesToHex([UInt8](sig as Data))
  }

  func deleteKey() throws {
    let status = SecItemDelete(baseQuery() as CFDictionary)
    if status != errSecSuccess && status != errSecItemNotFound {
      throw DeviceKeyError(DeviceKeyCodes.deleteFailed, "could not delete device key")
    }
  }

  // ── single authoritative validation path (mirrors the Android validate()) ──

  private struct Validated { let privateKey: SecKey; let spkiHex: String; let info: [String: Any] }

  private func validate() throws -> Validated {
    let priv = try loadPrivateKey()

    // Attributes: EC / P-256 / private / hardware token (Secure Enclave).
    guard let attrs = SecKeyCopyAttributes(priv) as? [CFString: Any] else {
      throw DeviceKeyError(DeviceKeyCodes.keyInaccessible, "cannot read key attributes")
    }
    guard (attrs[kSecAttrKeyType] as? String) == (kSecAttrKeyTypeECSECPrimeRandom as String) else {
      throw DeviceKeyError(DeviceKeyCodes.keyIncompatible, "device key is not EC")
    }
    if let bits = attrs[kSecAttrKeySizeInBits] as? Int, bits != 256 {
      throw DeviceKeyError(DeviceKeyCodes.keyIncompatible, "device key is not P-256")
    }
    // Secure Enclave binding is required — a software/keychain EC key fails closed.
    guard (attrs[kSecAttrTokenID] as? String) == (kSecAttrTokenIDSecureEnclave as String) else {
      throw DeviceKeyError(DeviceKeyCodes.hardwareUnavailable, "hardware-backed key unavailable")
    }

    // Non-exportability proof: exporting the PRIVATE key must fail.
    if SecKeyCopyExternalRepresentation(priv, nil) != nil {
      throw DeviceKeyError(DeviceKeyCodes.keyExportable, "device key is unexpectedly exportable")
    }

    // Public key → 65-byte uncompressed point → 91-byte canonical SPKI.
    guard let pub = SecKeyCopyPublicKey(priv) else {
      throw DeviceKeyError(DeviceKeyCodes.keyIncompatible, "no public key")
    }
    var pubErr: Unmanaged<CFError>?
    guard let pointData = SecKeyCopyExternalRepresentation(pub, &pubErr) as Data? else {
      throw DeviceKeyError(DeviceKeyCodes.keyIncompatible, "cannot export public key")
    }
    let point = [UInt8](pointData)
    // Uncompressed P-256 point: 0x04 || X(32) || Y(32) = 65 bytes.
    guard point.count == 65, point[0] == 0x04 else {
      throw DeviceKeyError(DeviceKeyCodes.keyIncompatible, "unexpected public key encoding")
    }
    let spki = p256SpkiPrefix + point
    guard spki.count == 91 else {
      throw DeviceKeyError(DeviceKeyCodes.keyIncompatible, "unexpected SPKI length")
    }
    let spkiHex = bytesToHex(spki)
    let deviceId = bytesToHex([UInt8](SHA256.hash(data: Data(spki))))

    let info: [String: Any] = [
      "provider": "ios_secure_enclave",
      "keyVersion": 1,
      "deviceId": deviceId,
      "publicKeySpkiHex": spkiHex,
      "hardwareBacked": true,
      "nonExportable": true,
      "securityLevel": "secure_enclave",
    ]
    return Validated(privateKey: priv, spkiHex: spkiHex, info: info)
  }

  // ── keychain / Secure Enclave helpers ──

  private func baseQuery() -> [CFString: Any] {
    return [
      kSecClass: kSecClassKey,
      kSecAttrApplicationTag: tag,
      kSecAttrKeyType: kSecAttrKeyTypeECSECPrimeRandom,
    ]
  }

  // loadPrivateKey returns the keychain-resident SE private key, or throws
  // key_missing when absent / key_inaccessible on an unexpected error.
  private func loadPrivateKey() throws -> SecKey {
    var query = baseQuery()
    query[kSecReturnRef] = true
    var item: CFTypeRef?
    let status = SecItemCopyMatching(query as CFDictionary, &item)
    if status == errSecItemNotFound {
      throw DeviceKeyError(DeviceKeyCodes.keyMissing, "device key is missing")
    }
    guard status == errSecSuccess, let ref = item else {
      throw DeviceKeyError(DeviceKeyCodes.keyInaccessible, "device key is inaccessible")
    }
    return (ref as! SecKey)
  }

  private func generateKey() throws {
    // A truly absent enclave (Simulator / unsupported device) fails closed here
    // rather than being conflated with a device-locked or access error below.
    guard SecureEnclave.isAvailable else {
      throw DeviceKeyError(DeviceKeyCodes.hardwareUnavailable, "hardware-backed key unavailable")
    }
    var acError: Unmanaged<CFError>?
    guard let access = SecAccessControlCreateWithFlags(
      kCFAllocatorDefault,
      kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
      .privateKeyUsage,
      &acError
    ) else {
      throw DeviceKeyError(DeviceKeyCodes.nativeOperationFailed, "access control creation failed")
    }
    let attributes: [CFString: Any] = [
      kSecAttrKeyType: kSecAttrKeyTypeECSECPrimeRandom,
      kSecAttrKeySizeInBits: 256,
      kSecAttrTokenID: kSecAttrTokenIDSecureEnclave,
      kSecPrivateKeyAttrs: [
        kSecAttrIsPermanent: true,
        kSecAttrApplicationTag: tag,
        kSecAttrAccessControl: access,
      ] as [CFString: Any],
    ]
    var genError: Unmanaged<CFError>?
    guard SecKeyCreateRandomKey(attributes as CFDictionary, &genError) != nil else {
      throw mapGenerationError(genError)
    }
  }

  // mapGenerationError converts a SecKeyCreateRandomKey CFError to a SAFE typed
  // code without leaking raw provider detail or key metadata. Device-locked /
  // access errors are not "hardware unavailable" — the identity is intact but
  // temporarily inaccessible, so recovery policy must differ:
  //   - locked / auth failure     -> key_inaccessible
  //   - enclave unavailable        -> hardware_unavailable
  //   - anything else (contract)   -> native_operation_failed
  private func mapGenerationError(_ error: Unmanaged<CFError>?) -> DeviceKeyError {
    guard let cf = error?.takeRetainedValue() else {
      return DeviceKeyError(DeviceKeyCodes.nativeOperationFailed, "key generation failed")
    }
    let status = OSStatus(truncatingIfNeeded: CFErrorGetCode(cf))
    switch status {
    case errSecInteractionNotAllowed, errSecAuthFailed:
      return DeviceKeyError(DeviceKeyCodes.keyInaccessible, "device key is inaccessible")
    case errSecUnimplemented, errSecNotAvailable:
      return DeviceKeyError(DeviceKeyCodes.hardwareUnavailable, "hardware-backed key unavailable")
    default:
      return DeviceKeyError(DeviceKeyCodes.nativeOperationFailed, "key generation failed")
    }
  }

  // ── hex codecs (lowercase, strict) ──

  private func hexToBytes(_ s: String) throws -> Data {
    let chars = Array(s.utf8)
    guard chars.count % 2 == 0 else {
      throw DeviceKeyError(DeviceKeyCodes.nativeOperationFailed, "bad input")
    }
    var out = [UInt8](); out.reserveCapacity(chars.count / 2)
    var i = 0
    while i < chars.count {
      guard let hi = hexNibble(chars[i]), let lo = hexNibble(chars[i + 1]) else {
        throw DeviceKeyError(DeviceKeyCodes.nativeOperationFailed, "bad input")
      }
      out.append((hi << 4) | lo)
      i += 2
    }
    return Data(out)
  }

  private func hexNibble(_ c: UInt8) -> UInt8? {
    switch c {
    case 0x30...0x39: return c - 0x30          // 0-9
    case 0x61...0x66: return c - 0x61 + 10      // a-f
    case 0x41...0x46: return c - 0x41 + 10      // A-F
    default: return nil
    }
  }

  private func bytesToHex(_ b: [UInt8]) -> String {
    let digits = Array("0123456789abcdef".utf8)
    var out = [UInt8](); out.reserveCapacity(b.count * 2)
    for byte in b {
      out.append(digits[Int(byte >> 4)])
      out.append(digits[Int(byte & 0x0f)])
    }
    return String(decoding: out, as: UTF8.self)
  }
}
