#!/bin/sh
# M3-auth-1B MANDATORY native gate — runs the real iOS Secure Enclave XCTest on a
# connected physical device.
#
# SEPARATE from scripts/build-gate.sh (which does not compile or run any iOS
# Swift). The Secure Enclave is UNAVAILABLE on the Simulator, so a build-only or
# Simulator run can NOT satisfy this gate: it selects a physical device by UDID
# and fails loudly when none is present. A generic/build-only destination is
# never accepted as a hardware PASS.
#
# Usage:
#   sh scripts/ios-native-gate.sh
#
# Steps:
#   1. require xcodebuild + a physical iOS device (by UDID)
#   2. clean Expo prebuild (reproducible generated iOS project) + pod install
#   3. verify the test scheme exists, then run it on the device (id=<UDID>)
set -e

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MOBILE_DIR="$PROJECT_ROOT/mobile"
TEST_SCHEME="${IOS_TEST_SCHEME:-PokitDeviceKey-Unit-Tests}"

echo "=== M3-auth-1B iOS native gate ==="

if ! command -v xcodebuild >/dev/null 2>&1; then
  echo "FAILED: xcodebuild not found — Xcode and a connected iOS device are required." >&2
  exit 1
fi

# Select a PHYSICAL iOS device UDID: take the entries before the Simulators
# section, keep only lines carrying an iOS version "(X.Y)" (excludes the Mac and
# section headers), and extract the trailing parenthesised UDID.
UDID="$(xcrun xctrace list devices 2>/dev/null \
  | awk '/== Simulators ==/{exit} /\([0-9]+\.[0-9]+(\.[0-9]+)?\) \(/{print}' \
  | sed -E 's/.*\(([0-9A-Fa-f-]+)\)[[:space:]]*$/\1/' \
  | head -1)"

if [ -z "$UDID" ]; then
  echo "FAILED: no physical iOS device connected. The Secure Enclave gate requires" >&2
  echo "        a real device — a Simulator has no enclave and cannot pass this gate." >&2
  exit 1
fi
echo "Using physical device: $UDID"

cd "$MOBILE_DIR"
echo "--- clean prebuild (ios) ---"
npx expo prebuild --clean --platform ios --no-install

cd "$MOBILE_DIR/ios"
echo "--- pod install ---"
pod install

WORKSPACE="$(ls -1 *.xcworkspace 2>/dev/null | head -1)"
if [ -z "$WORKSPACE" ]; then
  echo "FAILED: no .xcworkspace generated by prebuild/pod install." >&2
  exit 1
fi
echo "Workspace: $WORKSPACE"

# Verify the test scheme actually exists — a missing scheme must fail the gate,
# not silently run nothing.
if ! xcodebuild -list -workspace "$WORKSPACE" 2>/dev/null | grep -qw "$TEST_SCHEME"; then
  echo "FAILED: test scheme '$TEST_SCHEME' not found. Available schemes:" >&2
  xcodebuild -list -workspace "$WORKSPACE" 2>/dev/null | sed -n '/Schemes:/,$p' >&2
  echo "Set IOS_TEST_SCHEME to the correct scheme and re-run." >&2
  exit 1
fi

echo "--- xcodebuild test (scheme $TEST_SCHEME) on device $UDID ---"
# Real device destination (id=<UDID>). Never a generic/build-only destination:
# the enclave sign/verify tests must actually execute on hardware.
xcodebuild test \
  -workspace "$WORKSPACE" \
  -scheme "$TEST_SCHEME" \
  -destination "id=$UDID"

echo "=== iOS NATIVE GATE PASSED (device $UDID) ==="
echo "To capture the Go interop fixture, copy the app container's"
echo "  Documents/ios_signature_fixture.json into"
echo "  $PROJECT_ROOT/companion-daemon/internal/devicetrust/testdata/ios_signature_fixture.json"
