package expo.modules.pokitdevicekey

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.security.keystore.StrongBoxUnavailableException
import java.security.KeyFactory
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.MessageDigest
import java.security.PrivateKey
import java.security.Signature
import java.security.interfaces.ECPublicKey
import java.security.spec.ECGenParameterSpec

// Typed device-key failure. `code` is a stable machine-readable identifier from
// the shared vocabulary; the message is safe (no key material, alias, path, or
// provider internals). The Expo module maps this to a CodedException so JS
// receives the code independently of the message.
class DeviceKeyException(val code: String, message: String) : Exception(message)

// Stable error-code vocabulary (mirrored in the TS wrapper).
object DeviceKeyCodes {
  const val KEY_MISSING = "key_missing"
  const val KEY_INVALIDATED = "key_invalidated"
  const val KEY_INACCESSIBLE = "key_inaccessible"
  const val HARDWARE_UNAVAILABLE = "hardware_unavailable"
  const val KEY_EXPORTABLE = "key_exportable"
  const val KEY_INCOMPATIBLE = "key_incompatible"
  const val NATIVE_OPERATION_FAILED = "native_operation_failed"
  const val DELETE_FAILED = "delete_failed"
}

// PokitDeviceKeyStore holds the Android Keystore logic, free of any Expo/React
// dependency so instrumentation exercises the real Keystore directly. The
// private scalar is created inside AndroidKeyStore and never leaves it.
class PokitDeviceKeyStore(private val alias: String = DEFAULT_ALIAS) {

  companion object {
    const val DEFAULT_ALIAS = "pokit.device.identity.v1"
    private const val KEYSTORE = "AndroidKeyStore"
    private val LOCK = Any()

    // Test-only override. Production leaves this false so a software-only
    // Keystore fails closed. Internal — unreachable from JS or a release path.
    @JvmStatic
    internal var allowSoftwareKeystoreForTest: Boolean = false
  }

  // Validated bundle: the private-key handle plus the public identity metadata.
  // Private material is never exposed beyond the in-process signing call.
  private class Validated(val entry: KeyStore.PrivateKeyEntry, val info: Map<String, Any?>)

  private fun keyStore(): KeyStore = try {
    KeyStore.getInstance(KEYSTORE).also { it.load(null) }
  } catch (e: Exception) {
    throw DeviceKeyException(DeviceKeyCodes.KEY_INACCESSIBLE, "keystore unavailable")
  }

  fun getSupport(): String = try {
    keyStore()
    "supported"
  } catch (e: Exception) {
    "not_implemented"
  }

  fun hasKey(): Boolean = keyStore().containsAlias(alias)

  // ensureKey is atomic (whole body under LOCK). Creation ownership is explicit:
  // an alias that existed before this call is validated and returned as-is and is
  // NEVER deleted/replaced; a key generated by THIS call that fails validation
  // (before its identity is exposed) is the only thing this call may clean up.
  fun ensureKey(): Map<String, Any?> = synchronized(LOCK) {
    val ks = keyStore()
    val createdByThisCall = !ks.containsAlias(alias)
    if (createdByThisCall) {
      generateKey()
    }
    try {
      validate().info
    } catch (e: DeviceKeyException) {
      if (createdByThisCall) {
        // Roll back only the key this call created; preserve the typed error.
        try {
          ks.deleteEntry(alias)
        } catch (ce: Exception) {
          throw DeviceKeyException(DeviceKeyCodes.NATIVE_OPERATION_FAILED, "cleanup of failed new key failed")
        }
      }
      // Existing alias: fail closed WITHOUT deleting/replacing it.
      throw e
    }
  }

  fun getKeyInfo(): Map<String, Any?> = validate().info

  fun getPublicKeySpki(): String = validate().info["publicKeySpkiHex"] as String

  // sign passes the SAME full policy validation as ensureKey/getKeyInfo before
  // producing any signature — a software/P-384/wrong-digest/non-EC alias can
  // never sign, even if it already exists at the alias.
  fun sign(messageHex: String): String {
    val message = hexToBytes(messageHex)
    val v = validate() // full key policy — throws before any signing
    return try {
      val sig = Signature.getInstance("SHA256withECDSA")
      sig.initSign(v.entry.privateKey)
      sig.update(message)
      bytesToHex(sig.sign()) // ASN.1 DER
    } catch (e: DeviceKeyException) {
      throw e
    } catch (e: Exception) {
      throw DeviceKeyException(DeviceKeyCodes.NATIVE_OPERATION_FAILED, "signing failed")
    }
  }

  fun deleteKey() {
    try {
      keyStore().deleteEntry(alias)
    } catch (e: DeviceKeyException) {
      throw e
    } catch (e: Exception) {
      throw DeviceKeyException(DeviceKeyCodes.DELETE_FAILED, "could not delete device key")
    }
  }

  // ── single authoritative validation path ──

  private fun validate(): Validated {
    val ks = keyStore()
    if (!ks.containsAlias(alias)) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_MISSING, "device key is missing")
    }
    val entry = try {
      ks.getEntry(alias, null)
    } catch (e: DeviceKeyException) {
      throw e
    } catch (e: Exception) {
      // UnrecoverableKeyException / KeyStoreException / KeyPermanentlyInvalidated
      throw DeviceKeyException(DeviceKeyCodes.KEY_INACCESSIBLE, "device key is inaccessible")
    }
    if (entry !is KeyStore.PrivateKeyEntry) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_INCOMPATIBLE, "not a private-key entry")
    }
    // Android Keystore private keys do NOT implement ECPrivateKey — validate via
    // algorithm + KeyInfo + the certificate public params, never by casting.
    val priv: PrivateKey = entry.privateKey
    if (priv.algorithm != KeyProperties.KEY_ALGORITHM_EC) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_INCOMPATIBLE, "device key is not EC")
    }
    if (priv.encoded != null) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_EXPORTABLE, "device key is unexpectedly exportable")
    }

    val keyInfo = keyInfoOf(priv)
      ?: throw DeviceKeyException(DeviceKeyCodes.KEY_INACCESSIBLE, "cannot read key info")
    if ((keyInfo.purposes and KeyProperties.PURPOSE_SIGN) == 0) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_INCOMPATIBLE, "device key does not permit signing")
    }
    if (keyInfo.digests.none { it == KeyProperties.DIGEST_SHA256 }) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_INCOMPATIBLE, "device key does not permit SHA-256")
    }

    val level = securityLevelString(keyInfo)
    val hardwareBacked = level == "strongbox" || level == "tee"
    if (!hardwareBacked && !allowSoftwareKeystoreForTest) {
      // Fail closed. validate() NEVER deletes the alias — an existing paired
      // identity must survive a rejection. Cleanup of a just-generated unusable
      // key is owned solely by ensureKey().
      throw DeviceKeyException(DeviceKeyCodes.HARDWARE_UNAVAILABLE, "hardware-backed key unavailable")
    }

    val cert = entry.certificate
      ?: throw DeviceKeyException(DeviceKeyCodes.KEY_INCOMPATIBLE, "no public certificate")
    val pub = cert.publicKey
    if (pub !is ECPublicKey) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_INCOMPATIBLE, "public key is not EC")
    }
    val params = pub.params
    if (params.curve.field.fieldSize != 256 || params.order.bitLength() != 256) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_INCOMPATIBLE, "public key is not P-256")
    }
    val spki = pub.encoded
    if (spki == null || spki.size != 91) {
      throw DeviceKeyException(DeviceKeyCodes.KEY_INCOMPATIBLE, "unexpected public key encoding")
    }
    val spkiHex = bytesToHex(spki)
    val deviceId = bytesToHex(MessageDigest.getInstance("SHA-256").digest(spki))

    return Validated(entry, mapOf(
      "provider" to "android_keystore",
      "keyVersion" to 1,
      "deviceId" to deviceId,
      "publicKeySpkiHex" to spkiHex,
      "hardwareBacked" to hardwareBacked,
      "nonExportable" to true,
      "securityLevel" to level
    ))
  }

  private fun generateKey() {
    val build: (Boolean) -> KeyGenParameterSpec = { strongBox ->
      val b = KeyGenParameterSpec.Builder(alias, KeyProperties.PURPOSE_SIGN)
        .setAlgorithmParameterSpec(ECGenParameterSpec("secp256r1"))
        .setDigests(KeyProperties.DIGEST_SHA256)
      if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
        b.setIsStrongBoxBacked(true)
      }
      b.build()
    }
    try {
      val kpg = KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, KEYSTORE)
      try {
        kpg.initialize(build(true))
        kpg.generateKeyPair()
      } catch (e: StrongBoxUnavailableException) {
        kpg.initialize(build(false))
        kpg.generateKeyPair()
      }
    } catch (e: Exception) {
      throw DeviceKeyException(DeviceKeyCodes.NATIVE_OPERATION_FAILED, "key generation failed")
    }
  }

  private fun keyInfoOf(priv: PrivateKey): KeyInfo? = try {
    KeyFactory.getInstance(priv.algorithm, KEYSTORE).getKeySpec(priv, KeyInfo::class.java)
  } catch (e: Exception) {
    null
  }

  @Suppress("DEPRECATION")
  private fun securityLevelString(keyInfo: KeyInfo): String {
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
      return when (keyInfo.securityLevel) {
        KeyProperties.SECURITY_LEVEL_STRONGBOX -> "strongbox"
        KeyProperties.SECURITY_LEVEL_TRUSTED_ENVIRONMENT -> "tee"
        KeyProperties.SECURITY_LEVEL_SOFTWARE -> "os_keystore"
        else -> "unknown"
      }
    }
    return if (keyInfo.isInsideSecureHardware) "tee" else "os_keystore"
  }

  private fun hexToBytes(s: String): ByteArray {
    if (s.length % 2 != 0) throw DeviceKeyException(DeviceKeyCodes.NATIVE_OPERATION_FAILED, "bad input")
    val out = ByteArray(s.length / 2)
    var i = 0
    while (i < s.length) {
      val hi = Character.digit(s[i], 16)
      val lo = Character.digit(s[i + 1], 16)
      if (hi < 0 || lo < 0) throw DeviceKeyException(DeviceKeyCodes.NATIVE_OPERATION_FAILED, "bad input")
      out[i / 2] = ((hi shl 4) or lo).toByte()
      i += 2
    }
    return out
  }

  private fun bytesToHex(b: ByteArray): String {
    val sb = StringBuilder(b.size * 2)
    for (byte in b) sb.append(String.format("%02x", byte))
    return sb.toString()
  }
}
